# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a16d4bef50f9dcd27eb5417000792927"
name = "skincare-delivery-app"
application_url = "https://jessia-unpanicky-meagan.ngrok-free.dev"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = ["orders/create"]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_locations, read_markets_home, read_customers, write_customers, write_products, write_orders, read_inventory, write_inventory"

[auth]
redirect_urls = [ "https://jessia-unpanicky-meagan.ngrok-free.dev/api/auth" ]
